### ISSUE TITLE
Does not fix REI tooltips

### ISSUE THREAD

**Issue by J-0-E-L** [kyrptonaught/tooltipfix#13]
Enchantment Descriptions (version 0.6.1 for 1.18.1) item tooltips in REI are not fixed. Using ToolTipFix version 1.0.4 for 1.18.1. The enchantment used to generate such a long tooltip is from the mod "Fabric Enchantments" (Vanilla respiration should do the trick though).

![2022-01-09_23 14 11](https://user-images.githubusercontent.com/97390124/148682450-316f0651-4248-4206-882e-e51e334656b4.png)

**Comment by foul-fortune-feline** [comment]
In case anyone is wondering the cause of the issue, REI has its own tooltips it uses, and therefore u need an REI plugin to get this to work there. This mod could implement that without adding it as a requirement but I'm unsure how much work it would be. The [REI wiki](https://shedaniel.gitbook.io/roughly-enough-items/) is a good resource if a tad hard on the eyes if I'm being totally candid

**Comment by kyrptonaught** [comment]
This should be fixed in 1.1.0

**Comment by ChristopherHaws** [comment]
I am running 1.1.0-1.19 and I am still having an issue with REI tooltips:
![2022-11-29_19 38 02](https://user-images.githubusercontent.com/5934505/204726716-f43c5250-d57e-41e6-b235-0d15af3ba254.png)

**Comment by ChristopherHaws** [comment]
There is still an issue with the tooltip getting cut off on the right hand side of the screen:
![2022-12-01_00 48 24](https://user-images.githubusercontent.com/5934505/205008960-33f64312-c007-41bf-ac20-8aaa311f3586.png)
